In [ ]:
import numpy as np
import random

In [86]:
def generate_A(n, m):
    A = [[random.randint(1, 10) for _ in range(m)] for _ in range(n)]
    return np.array(A, dtype=float)

In [87]:
# 1. Wypisanie macierzy A

A = generate_A(5, 6)
n, m = A.shape

print("1. A:\n", A)

1. A:
 [[ 1.  6.  1.  3.  1. 10.]
 [ 6.  8.  7. 10.  5. 10.]
 [ 7.  1.  8.  5.  2.  5.]
 [ 8.  3.  8.  7.  7.  2.]
 [ 1.  3. 10.  3.  5.  1.]]


In [88]:
# 2. Wyliczenie A A^T

AAT = A @ A.T
print("\n2. A A^T:\n", AAT)


2. A A^T:
 [[148. 196.  88.  82.  53.]
 [196. 374. 216. 253. 165.]
 [ 88. 216. 168. 182. 120.]
 [ 82. 253. 182. 239. 155.]
 [ 53. 165. 120. 155. 145.]]


In [90]:
# 3. Lambda_i i wektory własne

eigvals_U, U = np.linalg.eigh(AAT)

idx = np.argsort(eigvals_U)[::-1]
eigvals_U = eigvals_U[idx]
U = U[:, idx]


print("\n3. Lambda (AAT):\n", eigvals_U)



3. Lambda (AAT):
 [882.19305007 136.41976673  34.83692258  17.83495383   2.71530678]


In [91]:
print("\n4. U:\n", U)

sigma = np.sqrt(np.clip(eigvals_U, 0, None))

print("\n4. S:\n", sigma)


4. U:
 [[-0.29623956 -0.7044748   0.20578629 -0.16015708 -0.58988057]
 [-0.63526222 -0.33372816 -0.02940798  0.30917729  0.62338752]
 [-0.40730963  0.18439336 -0.40492725 -0.79539141  0.05902862]
 [-0.48273584  0.4303543  -0.31695392  0.4704922  -0.50984173]
 [-0.33128388  0.41609499  0.83208251 -0.15731721  0.0024371 ]]

4. S:
 [29.7017348  11.67988727  5.90228113  4.22314502  1.64781879]


In [92]:
V = np.zeros((m, n))

for i in range(len(sigma)):
    if sigma[i] > 1e-10:
        V[:, i] = (A.T @ U[:, i]) / sigma[i]

In [93]:
print("\n6. V^T:\n", V.T)


6. V^T:
 [[-0.37547136 -0.32688003 -0.51095593 -0.45959913 -0.31387864 -0.42584454]
 [ 0.2091492  -0.3572751   0.5169878  -0.02294322  0.26443972 -0.70062827]
 [-0.76389129  0.36255685  0.43130887 -0.24122657  0.2017232  -0.01061936]
 [-0.06303662  0.39226913 -0.51342821  0.34472849  0.54504544 -0.40327475]
 [-0.31110933 -0.00932658  0.11633455  0.72689778 -0.5532115  -0.23487639]]


In [94]:
ATA = A.T @ A
print("\n7. A^T A:\n", ATA)


7. A^T A:
 [[151.  88. 173. 157. 106. 122.]
 [ 88. 119. 124. 133.  84. 154.]
 [173. 124. 278. 199. 158. 146.]
 [157. 133. 199. 192. 127. 172.]
 [106.  84. 158. 127. 104.  89.]
 [122. 154. 146. 172.  89. 230.]]


In [95]:
eigvals_V, V2 = np.linalg.eigh(ATA)

idx = np.argsort(eigvals_V)[::-1]
eigvals_V = eigvals_V[idx]
V2 = V2[:, idx]

sigma2 = np.sqrt(np.clip(eigvals_V, 0, None))

In [96]:
print("\n9. V2:\n", V2)
print("\n9. S2:\n", sigma2)


9. V2:
 [[-0.37547136 -0.2091492   0.76389129  0.06303662 -0.31110933  0.36191895]
 [-0.32688003  0.3572751  -0.36255685 -0.39226913 -0.00932658  0.69288846]
 [-0.51095593 -0.5169878  -0.43130887  0.51342821  0.11633455  0.09207634]
 [-0.45959913  0.02294322  0.24122657 -0.34472849  0.72689778 -0.28780873]
 [-0.31387864 -0.26443972 -0.2017232  -0.54504544 -0.5532115  -0.43329215]
 [-0.42584454  0.70062827  0.01061936  0.40327475 -0.23487639 -0.33146077]]

9. S2:
 [29.7017348  11.67988727  5.90228113  4.22314502  1.64781879  0.        ]


In [97]:
U2 = np.zeros((n, m))

for i in range(len(sigma2)):
    if sigma2[i] > 1e-10:
        U2[:, i] = (A @ V2[:, i]) / sigma2[i]

In [98]:
print("\n11. U2:\n", U2)


11. U2:
 [[-0.29623956  0.7044748  -0.20578629  0.16015708 -0.58988057  0.        ]
 [-0.63526222  0.33372816  0.02940798 -0.30917729  0.62338752  0.        ]
 [-0.40730963 -0.18439336  0.40492725  0.79539141  0.05902862  0.        ]
 [-0.48273584 -0.4303543   0.31695392 -0.4704922  -0.50984173  0.        ]
 [-0.33128388 -0.41609499 -0.83208251  0.15731721  0.0024371   0.        ]]


In [99]:
A_rec_1 = np.zeros((n, m))
A_rec_2 = np.zeros((n, m))

r = min(n, m)

for i in range(r):
    A_rec_1 += sigma[i] * np.outer(U[:, i], V[:, i])
    A_rec_2 += sigma2[i] * np.outer(U2[:, i], V2[:, i])

print("\nA_rec_1: ", A_rec_1)
print("\nA_rec_2: ", A_rec_2)

print("\n12. Błąd AAT:", np.linalg.norm(A - A_rec_1))
print("12. Błąd ATA:", np.linalg.norm(A - A_rec_2))
print("12. Różnica metod:", np.linalg.norm(A_rec_1 - A_rec_2))


A_rec_1:  [[ 1.  6.  1.  3.  1. 10.]
 [ 6.  8.  7. 10.  5. 10.]
 [ 7.  1.  8.  5.  2.  5.]
 [ 8.  3.  8.  7.  7.  2.]
 [ 1.  3. 10.  3.  5.  1.]]

A_rec_2:  [[ 1.  6.  1.  3.  1. 10.]
 [ 6.  8.  7. 10.  5. 10.]
 [ 7.  1.  8.  5.  2.  5.]
 [ 8.  3.  8.  7.  7.  2.]
 [ 1.  3. 10.  3.  5.  1.]]

12. Błąd AAT: 2.5019215181393538e-14
12. Błąd ATA: 4.216860310682953e-14
12. Różnica metod: 3.8270339404765685e-14


In [100]:
rank = np.linalg.matrix_rank(A)
null_dim = m - rank

print("\n13. dim R(A):", rank)
print("13. dim N(A):", null_dim)


13. dim R(A): 5
13. dim N(A): 1
